import {
  ElContainer,
  ElHeader,
  ElMain,
  ElAside,
  ElCard,
  ElPagination,
  ElLoading,
  ElRow,
  ElCol,
  ElButton,
  ElAlert,
  ElTabs,
  ElTabPane,
  ElBreadcrumb,
  ElBreadcrumbItem,
  ElSteps,
  ElStep,
  ElMenu,
  ElSubmenu,
  ElMenuItem,
  ElMenuItemGroup,
  ElSwitch,
  ElTable,
  ElTableColumn,
  ElInput,
  ElDialog,
  ElForm,
  ElFormItem,
  ElSelect,
  ElOption,
  ElTag,
  ElTree,
  ElCascader,
} from 'element-plus';
import 'element-plus/packages/theme-chalk/src/base.scss';
// element-plus
// international
import lang from 'element-plus/lib/locale/lang/zh-cn';
import 'dayjs/locale/zh-cn';
import locale from 'element-plus/lib/locale';
locale.use(lang);

const components = [
  ElContainer,
  ElHeader,
  ElMain,
  ElAside,
  ElCard,
  ElPagination,
  ElLoading,
  ElRow,
  ElCol,
  ElButton,
  ElAlert,
  ElTabs,
  ElTabPane,
  ElBreadcrumb,
  ElBreadcrumbItem,
  ElSteps,
  ElStep,
  ElMenu,
  ElSubmenu,
  ElMenuItem,
  ElMenuItemGroup,
  ElSwitch,
  ElTable,
  ElTableColumn,
  ElInput,
  ElDialog,
  ElForm,
  ElFormItem,
  ElSelect,
  ElOption,
  ElTag,
  ElTree,
  ElCascader,
];

export default components;
